/*
 * RECOMENDADOR ADAPTATIVO DE RUTAS DE VIAJE DENTRO DE LA CIUDAD
 * Trabajo Fin de Grado
 * Curso 2015-2016
 * EditorGrafos
 */
package editorgrafos;

import data.*;
import controller.*;

/**
 * Clase que contiene el metodo main del proyecto.
 * Dicha clase incluye el JFrame con el diseño del interfaz grafico.
 * @author Daniel Hernández Bélanger
 * @version 1.0
 */
public class EditorGrafos extends javax.swing.JFrame {
    
    /**Variable privada: Objeto que contiene el modelo del proyecto*/
    private Model model;
    /**Variable privada: Objeto que contiene el controlador del proyecto*/
    private Controller controller;

    /**
     * Constructor EditorGrafos.
     * Crea un nuevo objeto EditorGrafos.
     */
    public EditorGrafos() {
        model = new Model();
        controller = new Controller(model);
        controller.setFrame(this);
        initComponents();
    }
    
    /**
     * Metodo que devuelve el objeto model que contiene la clase EditorGrafo 
     * @return Referencia al objeto Model. 
     * @since incluido desde la version 1.0
     */
    public Model getModel() {
        return model;
    }
    
    /**
     * Metodo que devuelve el objeto controller que contiene la clase EditorGrafo 
     * @return Referencia al objeto Controller. 
     * @since incluido desde la version 1.0
     */
    public Controller getController() {
        return controller;
    }

    /** Metodo que hace referencia al evento de hacer click con el raton.
     * Cuando llega un evento de hacer click con el raton se selecciona un nodo
     * en las coordenadas donde se encuentra el raton y se llama al metodo
     * correspondiente. Ademas se llama a la funcion repaint().
     * @param evt Referencia al evento del interfaz grafico
     * @since incluido desde la version 1.0
     */
    public void mouseClickedinPanelMap(java.awt.event.MouseEvent evt) {
        if (addNodeButton.isSelected()) {
            controller.addNode(evt.getX(), evt.getY());
        } else if (addLinkButton.isSelected()) {
            controller.addLink(evt.getX(), evt.getY());
        } else if (moveButton.isSelected()){
            controller.moveNode(evt.getX(), evt.getY());
        } else if (deleteButton.isSelected()){
            controller.deleteNode(evt.getX(), evt.getY());
        } else if (deleteLinkButton.isSelected()){
            controller.deleteLink(evt.getX(), evt.getY());
        }
        
        newJPanel1.repaint();
        newJPanel1.frame.getModel().getGraph().saveData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMode = new javax.swing.ButtonGroup();
        newJPanel1 = new editorgrafos.PanelMap(this);
        jPanel2 = new javax.swing.JPanel();
        addNodeButton = new javax.swing.JRadioButton();
        addLinkButton = new javax.swing.JRadioButton();
        moveButton = new javax.swing.JRadioButton();
        deleteLinkButton = new javax.swing.JRadioButton();
        deleteButton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newJPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newJPanel1.setPreferredSize(new java.awt.Dimension(1500, 1200));

        javax.swing.GroupLayout newJPanel1Layout = new javax.swing.GroupLayout(newJPanel1);
        newJPanel1.setLayout(newJPanel1Layout);
        newJPanel1Layout.setHorizontalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        newJPanel1Layout.setVerticalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        buttonGroupMode.add(addNodeButton);
        addNodeButton.setSelected(true);
        addNodeButton.setText("Node");

        buttonGroupMode.add(addLinkButton);
        addLinkButton.setText("Link");

        buttonGroupMode.add(moveButton);
        moveButton.setText("Move");

        buttonGroupMode.add(deleteLinkButton);
        deleteLinkButton.setText("Delete Link");

        buttonGroupMode.add(deleteButton);
        deleteButton.setText("Delete Node");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLinkButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteLinkButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNodeButton)
                    .addComponent(addLinkButton)
                    .addComponent(moveButton)
                    .addComponent(deleteLinkButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(815, 815, 815))
            .addComponent(newJPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorGrafos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addLinkButton;
    private javax.swing.JRadioButton addNodeButton;
    private javax.swing.ButtonGroup buttonGroupMode;
    private javax.swing.JRadioButton deleteButton;
    private javax.swing.JRadioButton deleteLinkButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton moveButton;
    private editorgrafos.PanelMap newJPanel1;
    // End of variables declaration//GEN-END:variables
}
