/*
 * RECOMENDADOR ADAPTATIVO DE RUTAS DE VIAJE DENTRO DE LA CIUDAD
 * Trabajo Fin de Grado
 * Curso 2015-2016
 * EditorGrafos
 */
package editorgrafos;

import data.*;
import java.awt.Color;
import java.awt.Graphics;

/**
 * Clase que contiene el JPanel del proyecto.
 * Dicha clase se encarga de dibujar el mapa y los diferentes elementos que lo
 * componen.
 * @author Daniel Hernández Bélanger
 * @version 1.0
 */
public class PanelMap extends javax.swing.JPanel {
    
    /**Variable publica: Objeto que contiene el frame del interfaz grafico*/
    public EditorGrafos frame;
    /**Variable privada: Anchura del nodo*/
    private static int NODE_WIDTH=10;
    /**Variable privada: Imagen que contiene el mapa de la ciudad*/
    private java.awt.Image imagen;

    /**
     * Constructor PanelMap.
     * Crea un nuevo objeto PanelMap.
     */
    public PanelMap() {
        initComponents();
    }
    
    /**
     * Constructor PanelMap.
     * Crea un nuevo objeto PanelMap.
     */
    public PanelMap(EditorGrafos fr){
        this();
        frame = fr;
        imagen=java.awt.Toolkit.getDefaultToolkit().getImage("src/Archivos/planoGranada.png");
        setSize(imagen.getWidth(this),imagen.getHeight(this));
        //Cargamos los datos de la base de datos
        frame.getModel().getGraph().loadData();
    }

    /**
     * Metodo que pinta los componentes en el JFrame 
     * @param g Graphics donde se dibujara
     * @since incluido desde la version 1.0
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());
        g.drawImage(imagen,0,0,this);
        
        if(frame!=null && frame.getModel()!=null){
            drawNodes(g);
            drawLinks(g);
        }
    }
    
    /**
     * Metodo que dibuja los nodos sobre el mapa. 
     * Dibujara los nodos como circulos de color rojo o verde y sobre ellos 
     * pintara tambien el numero de su etiqueta.
     * @param g Graphics donde se dibujara
     * @since incluido desde la version 1.0
     */
    public void drawNodes(Graphics g){
        for(Node node:frame.getModel().getGraph().getNodeList()){
            if(frame.getModel().getSelectedNode()==node){
                g.setColor(Color.GREEN);
            } else{
                g.setColor(Color.RED);
            }
            g.fillArc(node.getX()-NODE_WIDTH/2, node.getY()-NODE_WIDTH/2, NODE_WIDTH, NODE_WIDTH, 0, 360);
            g.setColor(Color.BLACK);
            if(Integer.parseInt(node.getLabel())<10)
                g.drawString(node.getLabel(), node.getX()-4, node.getY()+5);
            else if (Integer.parseInt(node.getLabel())<100)
                g.drawString(node.getLabel(), node.getX()-8, node.getY()+5);
            else
                g.drawString(node.getLabel(), node.getX()-12, node.getY()+5); 
        }
    }
    
    /**
     * Metodo que dibuja los enlaces sobre el mapa. 
     * Dibujara los como lineas de color azul
     * @param g Graphics donde se dibujara
     * @since incluido desde la version 1.0
     */
    public void drawLinks(Graphics g){
        g.setColor(Color.BLUE);
        for(Link link:frame.getModel().getGraph().getLinkList()){
            g.drawLine(link.getFrom().getX(), link.getFrom().getY(), 
                    link.getTo().getX(), link.getTo().getY());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMap.this.mouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /** Metodo que hace referencia al evento de hacer click con el raton.
     * Cuando llega un evento de hacer click con el raton se selecciono un nodo
     * en las coordenadas donde se encuentrra el raton.
     * @param evt Referencia al evento del interfaz grafico
     * @since incluido desde la version 1.0
     */
    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:
        frame.mouseClickedinPanelMap(evt);
    }//GEN-LAST:event_mouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
